services:
  - type: web
    name: autoval-backend
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    healthCheckPath: "/api/health"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5001
